---
- hosts: localhost
  vars:
    applications:
      - docker
      - docker-compose
      - git
    casks:
      - dotnet-sdk
      - firefox
      - google-chrome
      - iterm2
      - slack
      - visual-studio-code
    vs_exts:
      - ms-dotnettools.csharp
      - fakesharper.fakesharper
      - ms-azuretools.vscode-docker
      - k--kato.intellij-idea-keybindings
      - fernandoescolar.vscode-solution-explorer
    git_config:
      - pull.ff only
      - pull.rebase false
      - core.autocrlf input

  tasks:
    - name: Update homebrew
      homebrew:
        update_homebrew: yes

    - name: Install apps with brew
      homebrew:
        name: "{{ applications }}"
        state: present

    - name: Install apps with brew (casks)
      homebrew_cask:
        name: "{{ casks }}"
        state: present
        accept_external_apps: true

    - name: Add code to path
      shell: |
        cat << EOF >> ~/.zshrc
        export PATH="\$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
        EOF

    - name: Install visual studio code extensions
      shell: code --install-extension {{ item }}
      loop: "{{ vs_exts }}"

    - name: Git config
      shell: git config --global {{ item }}
      loop: "{{ git_config }}"